version = 1

test_patterns = [
  "concat/tests/**"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
  type_checker = "mypy"

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = []
  dependency_file_paths = ["language-concat/"]
  environment = ["nodejs"]
  module_system = "commonjs"
  dialect = "typescript"
  skip_doc_coverage = ["function-declaration", "function-expression", "arrow-function-expression", "method-definition"]

[[transformers]]
name = "prettier"
