repos:
  - repo: local
    hooks:
      - id: axblack
        name: axblack
        description: Run Axblack on Python code (fork of Black).
        entry: black --line-length 79
        language: system
        types: [python]
