repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        description: Run `ruff format` on Python code.
        entry: ruff format
        language: system
        types: [python]
