
# C:\Users\jason\Documents\GitHub\concat\parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = '71C1B7A276EBB6745B1F40D06106FCDE'
    
_lr_action_items = {'$end':([1,2,7,],[-1,0,-2,]),'IDENTIFIER':([3,],[4,]),'`':([0,5,9,],[3,7,-3,]),'STRING_LITERAL':([6,],[8,]),')':([8,],[9,]),'(':([4,],[6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'py_expr':([0,],[1,]),'py_func_call':([3,],[5,]),'module':([0,],[2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> module","S'",1,None,None,None),
  ('module -> py_expr','module',1,'p_module','parse.py',11),
  ('py_expr -> ` py_func_call `','py_expr',3,'p_py_expr','parse.py',16),
  ('py_func_call -> IDENTIFIER ( STRING_LITERAL )','py_func_call',4,'p_py_func_call','parse.py',21),
]
