[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
dependencies = [
  'astunparse>=1.3.0,<2',
  'parsy>=1.3.0,<2',
  'typing-extensions>=4',
]
dynamic = ["version"]
name = "concat"

[tool.hatch.version]
path = "concat/__init__.py"
pattern = "version = '(?P<version>.*)'"
