# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install test dependencies
      run: |
        pip install -e .[test]
    - name: Test
      run: |
        coverage run -m nose2 --pretty-assert concat.tests
    - name: Collect coverage into one file
      # https://stackoverflow.com/a/58859404
      if: always()
      run: |
        coverage combine
        coverage xml
        coverage lcov
    - name: Report test coverage to DeepSource
      if: always()
      uses: deepsourcelabs/test-coverage-action@master
      with:
        key: python
        coverage-file: coverage.xml
        dsn: ${{ secrets.DEEPSOURCE_DSN }}
    - name: Coveralls
      if: always()
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        # https://github.com/coverallsapp/github-action/issues/55#issuecomment-1137870701
        git-commit: ${{ github.event.pull_request.head.sha }}
        path-to-lcov: ./coverage.lcov
